### Base ZSH config for login shells
# This file is sourced by the Automator and by the Terminal

# Defaults
setopt EXTENDED_GLOB     # Enable ^negation, etc., in glob patterns
setopt NO_UNSET          # Error if you reference an undefined variable

# suppress compinit warning
typeset -g skip_global_compinit=1

# Suppress spurious warnings when NO_UNSET is set
export INSIDE_EMACS="${INSIDE_EMACS:-}"

# Activate Homebrew if it exists
if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export HOMEBREW_NO_ENV_HINTS=1
elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
    export HOMEBREW_NO_ENV_HINTS=1
fi

# Custom PATH add-ins
typeset -a extra_paths
extra_paths=(
    "$HOME/.myhome/bin"
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
)
export PATH="$(printf "%s:" "${extra_paths[@]}")$PATH"

### Interactive shell configuration
is_interactive_shell() { [[ $- == *i* ]]; }
if is_interactive_shell; then

fi