### Base ZSH config for login shells
# This file is sourced by the Automator and by the Terminal

# Defaults
setopt EXTENDED_GLOB     # Enable ^negation, etc., in glob patterns
setopt NO_UNSET          # Error if you reference an undefined variable

# Suppress spurious warnings when NO_UNSET is set
export INSIDE_EMACS="${INSIDE_EMACS:-}"

# Activate Homebrew if it exists (macOS or Linux)
if command -v brew >/dev/null 2>&1; then
    eval "$(brew shellenv)"
    export HOMEBREW_NO_ENV_HINTS=1
fi

# Custom PATH add-ins
typeset -a extra_paths
extra_paths=(
    "$HOME/.myhome/bin"
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
)
export PATH="$(printf "%s:" "${extra_paths[@]}")$PATH"

### Interactive shell configuration
is_interactive_shell() { [[ $- == *i* ]]; }
if is_interactive_shell; then

fi